name: code for deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - name: Setup Node.js for use with actions
    - uses: actions/setup-node@v1.1.0
      with:
        version: 10.x
        
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: install gulp
      run: | 
        npm install gulp 
        gulp 
        gulp default
      

